import { createSlice, type PayloadAction } from "@reduxjs/toolkit";

// It defines the shape of the authentical user object
interface User {
  id: string;
  email: string;
  role: "photographyCompany" | "agent";
}

// It defines the shape of the auth slice state
interface AuthState {
  token: string | null;
  user: User | null; // null means not logged in
  isLoading: boolean; // true while the login API call is in progress
  error: string | null;
}

// sets the default state before any action is dispatched
const initialState: AuthState = {
  token: null,
  user: null,
  isLoading: false,
  error: null,
};

// Creates the auth slice with its actions and reducer, createSlice automatically generate action creators and reducer
const authSlice = createSlice({
  name: "auth", // Namespace for this slice in Redux store
  initialState,
  reducers: {
    loginStart(state) {
      state.isLoading = true;
      state.error = null;
    },
    // when logged in success, stores token and user info
    loginSuccess(state, action: PayloadAction<{ token: string; user: User }>) {
      state.isLoading = false;
      state.token = action.payload.token;
      state.user = action.payload.user;
    },
    // when failed, stores the error message
    loginFailure(state, action: PayloadAction<string>) {
      state.isLoading = false;
      state.error = action.payload;
    },
    logout(state) {
      state.token = null;
      state.user = null;
    },
  },
});

export const { loginStart, loginSuccess, loginFailure, logout } =
  authSlice.actions;
export default authSlice.reducer; // the reducer here is generated by createSlice
